language: python
python:
  - 2.6
  - 2.7
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
install:
  - python bootstrap.py
  - bin/buildout -N
script:
  - bin/test -s Products.CMFPlomino
